defaults:
  - base_inference
  - inference
  - osut5: train_v30
  - diffusion: v1
  - _self_

model_path: 'Tiger14n/Mapperatorinator2'
version: 'Mapperatorinator2'      

audio_path: ''
output_path: './'         # Path to output directory
beatmap_path: ''
export_osz: true         # Export beatmap as .osz file
start_time: null          # Start time of audio to generate beatmap for
end_time: null          # End time of audio to generate beatmap for
add_to_beatmap: false     # Add generated content to the reference beatmap

# Conditional generation settings
gamemode: 0             # Gamemode of the beatmap
difficulty: 5.0    # Difficulty star rating to map
mapper_id: 10507407  # Mapper ID to use as style

# Inference settings
seed: null # Random seed
device: cuda           # Inference device (cpu/cuda)
lookback: 0.5            # Fraction of audio sequence to fill with tokens from previous inference window
lookahead: 0.4           # Fraction ossf audio sequence to skip at the end of the audio window
timing_leniency: 50  # Number of milliseconds of error to allow for timing generation
in_context: []          # Context types of other beatmap(s)
output_type: [MAP]    # Output type (map, timing)
temperature: 0.9 # Sampling temperature
top_p: 0.9
generate_positions: false